### PR TITLE
Fix constraint eq

### LINKED ISSUE #143: panic: ConstrainEq on unbound variables
```
(rule ((= x 1) (= y x) (= z y)) ())
(run 1)
```
panics, while
```
(rule ((= x 1) (= y x)) ())
(run 1)
```
does not.

Seems related to desugaring @oflatt?

This issue is blocking @clyben from fixing a follow-up issue of #93.

More details:

Currently, the program produces body
```
[AssignLit(x, 1), ConstrainEq(y, x), ConstrainEq(z, y)]
```
while the expected body is
```
[AssignLit(x, 1), AssignVar(y, x), AssignVar(z, y)]
```

(Note that we don't have AssignVar currently.)

`ConstraintEq`s are produced by `flatten_facts` and `flatten_equalities` on cases like `(= var1 var2)`.

We can also remove the checks since we are converting `NormFact::ConstrainEq` back to `Fact::Eq` anyway so it shouldn't matter, maybe?

### PR DESCRIPTION
**Pull request by clyben**
This PR fix #143 by adding a transformation on rules that substitute all x to y in both head and body when meeting (= x y) in the body. For example, `(rule ((= x 1) (= y x) (= z y)) ((set (f z) 1))` is transferred to `(rule ((= x 1) (= x x) (= z x)) ((set (f z) 1))` and then `(rule ((= x 1) (= x x) (= x x)) ((set (f x) 1))`. It also adds a new Type error similar to LocalAlreadyBound but with less information to deal with letting binding conflict in transformation.

After solving #143, PR #146 for seminaive should be able to go.

### CODE REVIEW

**Comment by oflatt** [comment]
This is a great fix @clyben 
Unfortunately, I also fixed this bug in the PR I'm working on #158 
I also did it as part of the existing desugaring functions, instead of as another pass on top of the desugared code.


I would recommend closing this PR for now, I'm hoping to get mine in soon.

**Comment by clyben** [comment]
> 

Could you add tests/constraint-eq.egg in my PR to your fork?

**Comment by oflatt** [comment]
Yep!

**Comment by oflatt** [comment]
Added to my PR and fixed! Thanks for great tests!

**Comment by oflatt** [comment]
Fixed by #158

**Comment by clyben** [comment]
ok I will close it.

**Comment by yihozhang** [comment]
@clyben Could you re-open this issue since #158 is not going to be merged in the near future?

**Comment by oflatt** [comment]
As far as I know this was fixed by #176 
let me know if that was not the case

**Comment by yihozhang** [comment]
Ah great, I didn't know that! The test from this PR seems to be passing in `main`, so I suggest closing this PR (again) and I'll make another PR porting the tests from this one.

@oflatt: It seems your #176 also subsumes #146, which was originally blocked by this PR. I will check if this is the case, and if so, we can close #146 as well.

**Comment by oflatt** [comment]
I think I also added the tests in this one to #176 but double check

**Pull request closed without merging**
