### PR TITLE
Add power operator to i64 and f64 sorts

### PR DESCRIPTION
**Pull request by DeLectionnes**

### CODE REVIEW

**Review by saulshanabrook — APPROVED** [review]
Thank you for the tests as well!

**Comment by DeLectionnes** [comment]
After review of the i64 interface in https://doc.rust-lang.org/std/primitive.i64.html, it seems that all power functions take a u32 as exponent instead of another i64.

Should I use the unsafe proposition that the test suite proposes, or should I only leave the f64 part ?

**Comment by saulshanabrook** [comment]
Maybe just leave the f64 then, that seems easiest.

**Comment by DeLectionnes** [comment]
Is there a way to run the test suite on my branch ? it did not transfer when I forked.

**Comment by saulshanabrook** [comment]
@DeLectionnes If you go to the actions tab on your fork you should be able to re-enable github actions

**Pull request merged**
