### PR TITLE
Fix rebuilding and extraction bugs for EqSort containers

### LINKED ISSUE #165: Container rebuild bug
Here's a failing test:

[https://egraphs-good.github.io/egglog/?program=XQAAgAA5AQAAAAAAAAAFCt5yvsWfR8X0ni3K7Yumf[…]6BBt6aN1pbCBmCx9E-YvCaNuOBCluRmTNujEjkyD_pWdKAA%253D%253D](https://egraphs-good.github.io/egglog/?program=XQAAgAA5AQAAAAAAAAAFCt5yvsWfR8X0ni3K7YumfVR1TYk-EyPSssEcokh3CAZu6_TDcuupRWyfc5MwMBo5yY3xyYVoQPF8l6kILbWDDKO558CajMq4vP_k_9_u3Ykzv6RMddSHpkohdNoezbxlfOi4q0rX-MiYi-LfMA4qAbmq4-bqwXVUcqAZTanfh2C4o3GVZpQ8CIOWTW5ypTZoJNJYGkUztOt6BBt6aN1pbCBmCx9E-YvCaNuOBCluRmTNujEjkyD_pWdKAA%253D%253D)

Here's a more complex test that should pass:

```
(datatype Math
  (Num i64))

(sort MathVec (Vec Math))


(let v1 (vec-of (Num 1) (Num 2)))
(let v2 (vec-of (Num 2) (Num 2)))

(union (Num 1) (Num 2))

(check (= v1 v2))

(function MyVec (MathVec) Math)

(MyVec v1)

(check (MyVec v2))

(check (= (MyVec v1) (MyVec v2)))

(let v3 (vec-of (Num 4) (Num 5)))

(union (Num 4) (Num 6))
(union (Num 5) (Num 7))

;; We don't have any (MyVec v3) yet
(fail (check (= (MyVec v3) (MyVec (vec-of (Num 6) (Num 7))))))

(MyVec v3)
(check (= (MyVec v3) (MyVec (vec-of (Num 6) (Num 7)))))```

### PR DESCRIPTION
**Pull request by yihozhang**
This small PR should fix #165. There might be other bugs (especially memory leaks) with containers.

Update: this PR also contains some other fixes and changes.
1. Extraction for containers (and primitives) is working correctly now.
2. Extractor is exposed and used in the `Sort` trait.

### CODE REVIEW

**Comment by mwillsey** [comment]
Looks like this is still in progress. Converted to draft.

**Comment by yihozhang** [comment]
@mwillsey It should be ready for review now. The last time I pushed the tests are passing locally but not in CI. The bug should now be fixed.

**Comment by mwillsey** [comment]
There seem to be conflicts. Can you merge main into this branch?

**Comment by yihozhang** [comment]
@mwillsey done

**Comment by oflatt** [comment]
Good changes!
Does this PR contain the test cases I sent in slack to you?

**Comment by yihozhang** [comment]
@oflatt Yeah it had the tests from #165 and I just added the test case you sent to me, though for the extraction used in test cases, there's no way of doing correctness checks besides manually staring at the output.

**Comment by oflatt** [comment]
Maybe we should add stronger extraction tests in the future, for example at least checking that the cost stayed the same. But for now good work! We should merge this

**Pull request merged**
