### PR TITLE
Add doctest to document extract()

### PR DESCRIPTION
**Pull request by gussmith23**

### CODE REVIEW

**Review by oflatt — CHANGES_REQUESTED** [review]
Really great improvement to the docs-
If you would be so kind, would you add a small text description of what the code does for the documentation? We shouldn't add code examples without descriptions.
(Optional) Also would be good to link to this function from the existing documentation of the `query-extract` command

**Comment by gussmith23** [comment]
Will do, but may have to wait til next week!

**Comment by gussmith23** [comment]
@oflatt done. Please feel free to suggest different wording in both changes!

**Review by oflatt — APPROVED** [review]
Thanks a bunch!

**Pull request merged**
