### PR TITLE
User Defined Generics RFC

### PR DESCRIPTION
**Pull request by saulshanabrook**
I wanted to share this draft of an "RFC" (although I based the structure loosely off the Python PEP format, like [this one on generics](https://peps.python.org/pep-0695/#summary-examples)) on adding user-defined generic types and functions to egglog.

Happy for any feedback here or to set up a call if that's easier.

i.e. Does it make sense? Are there any questions left after reading it? Any confusion about the rationale or the syntax?
What do you think of it? Do you think implementing it is viable? Would it be useful for any of your work?

### CODE REVIEW

**Comment by oflatt** [comment]
Thanks for the RFC @saulshanabrook!
Quick question: would it be possible to desugar all these problems with generics on the python side?
As in, the python bindings would generate egglog code, one function per instantiation.
That way, you could experiment with generics and we won't have to modify egglog (yet!)

Egglog is about to go through lots of cleanup, so it's not a great time to add complexity to the type system

**Comment by saulshanabrook** [comment]
Hey @oflatt yeah that makes sense. I believe it would be doable by generating new datatypes for each instantiation of a generic type.

For rewrites/rules that use generic types, they are generated for every pairwise combination of generic types that they use and are instantiated.

**Comment by saulshanabrook** [comment]
I don't think this needs to be considered right now, but re opening this bc I thought of an issue with the desugaring approach... 

If there is a rule that has facts that use type T and actions that create type List[T] what concrete types do you instantiate this with? It seems like at the limit it could be infinite if it applies recursively.

**Comment by saulshanabrook** [comment]
I'll re-close this actually and open an issue if I want to look more into how to implement generics as pre-processing step.

**Pull request closed without merging**
